---
  - name: Add Managers to the Swarm
    shell: "docker swarm join --token {{ hostvars['docker1']['manager_token']['stdout'] }} {{ hostvars['docker1']['ansible_default_ipv4']['address'] }}:2377"
    tags: swarm
