---
  - name: Install of Requrements Tools
    hosts: nodes
    become: yes
    become_user: root
    roles:
      - configure-hosts-file

  - name: Initialize Docker Swarm Cluster
    hosts: active
    become: yes
    become_user: root
    roles:
      - docker-swarm-init
    ignore_errors: true

  - name: Add Managers Swarm Cluster
    hosts: standby
    become: yes
    become_user: root
    roles:
      - docker-swarm-add-manager

  - name: Add Workers to the Swarm Cluster
    hosts: workers
    become: yes
    become_user: root
    roles:
      - docker-swarm-add-worker
